plugins { id 'com.android.application' }

android {
    namespace 'dev.irona.player'
    compileSdk 35
    buildToolsVersion '34.0.0'
    defaultConfig {
        applicationId 'dev.irona.player'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    signingConfigs {
        debug {
            storeFile rootProject.file('../.runtime/android-user/debug.keystore')
        }
    }
}

dependencies { implementation 'org.nanohttpd:nanohttpd:2.3.1' }
